apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: n16cdfq1q-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: n16cdfq1q-nodejs 
  name: n16cdfq1q-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: n16cdfq1q-nodejs 
